name: Terraform Deploy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push: {}

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform init
        uses: ./.github/actions/setup
      
      - name: Terraform test
        run: cd test && go test -v -timeout 2000s infra_test.go

      - name: Terraform deploy
        run: terraform apply --auto-approve

      - name: Terraform destroy
        run: terraform destroy --auto-approve